package com.ab.enums;

public enum ConfigProperties {
    URL,
    OVER_RIDE_REPORTS,
    PASSED_STEPS_SCREENSHOTS,
    FAILED_STEPS_SCREENSHOTS,
    SKIPPED_STEPS_SCREENSHOTS,
    RETRY_FAILED_TESTS
}
